[package]
name = "rust-social"
version = "0.1.0"
authors = ["Chloe Holmes 3782047 <s3782047@student.rmit.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
